<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Remove="Assets\race element icon 2.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.6" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.6" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.6" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.6" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.2.6">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.2.6" />
    <PackageReference Include="Material.Icons.Avalonia" Version="2.3.1" />
    <PackageReference Include="Neumorphism.Avalonia" Version="0.11.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\MainTopMenuView.axaml.cs">
      <DependentUpon>MainTopMenuView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Pages\OverlaySettingPages\ControlButtonsPanelView.axaml.cs">
      <DependentUpon>ControlButtonsPanelView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
